FROM node:18.13-alpine

WORKDIR /usr/src/app

COPY package*.json ./

# RUN yarn install

# COPY . .

# EXPOSE 4000

# CMD ["yarn", "dev"]

# FROM base as production

# ENV NODE_PATH=./dist

# RUN yarn build