FROM node:18.13-alpine

WORKDIR /home/node/app

COPY package*.json ./

# RUN yarn install
# && yarn cache clean

# COPY . .

EXPOSE 3000

# CMD ["yarn", "dev"]

# FROM base as production

# ENV NODE_PATH=./dist

# RUN yarn build